#!/usr/bin/env python3
"""ShedOS installer wizard.

Launched on tty1 of the live installer ISO (via run-installer.sh) — that's
what a fresh user sees in the VMware Fusion window. Collects:
  - optional masked OAuth-token override
  - persona preset (default / coding / sysadmin / researcher)
  - conversation style flags (terse / formal / emojis)

Writes /tmp/shedos-wizard.env, then execs installer.sh which sources the
env and applies the choices during apply_overlay. The token override is
passed via process environment only (never written to disk in cleartext).

This module exposes two implementations:
  - WizardApp (Textual) — full-screen modern TUI, used when textual is
    importable (run-installer.sh pip-installs it on first boot).
  - run_rich_wizard() — line-by-line fallback using rich/getpass, used
    when textual didn't install (e.g. no network).

Both write the identical /tmp/shedos-wizard.env and exec installer.sh.

Failure modes:
- Ctrl-C / EOF mid-wizard: exit with the existing baked-in defaults so
  installer.sh runs unchanged.
- run-installer.sh holds /run/shedos-installer.lock for the lifetime of
  the install, so concurrent ttys (tty2/tty3 getty) can't race here.
"""
import getpass
import os
import re
import sys

WIZARD_ENV = "/tmp/shedos-wizard.env"
INSTALLER = "/opt/shedos-installer/installer.sh"

PERSONA_PRESETS = [
    ("default",    "Default",
     "All-purpose ShedOS shell. Terse, tool-driven."),
    ("coding",     "Coding Assistant",
     "Software-engineering focused. Defaults to git, tests, small diffs."),
    ("sysadmin",   "Sysadmin",
     "OpenRC + apk fluent. Confirms destructive ops."),
    ("researcher", "Researcher",
     "Pulls papers / data, renders PDFs and figures. Cites sources."),
]

# --- Shared helpers ----------------------------------------------------------

def write_wizard_env(token_override, persona_name, style):
    lines = ["# Generated by wizard.py at install time", ""]
    if token_override:
        os.environ["TOKEN_OVERRIDE"] = token_override
    else:
        os.environ.pop("TOKEN_OVERRIDE", None)
    lines.append(f"PERSONA_NAME='{persona_name}'")
    lines.append(f"STYLE_TERSE={1 if style['terse'] else 0}")
    lines.append(f"STYLE_FORMAL={1 if style['formal'] else 0}")
    lines.append(f"STYLE_EMOJIS={1 if style['emojis'] else 0}")
    with open(WIZARD_ENV, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(WIZARD_ENV, 0o600)


def exec_installer():
    os.execv(INSTALLER, [INSTALLER])


def looks_like_token(s):
    return bool(re.match(r"^sk-ant-oat\d+-", s.strip()))


def token_display(token_override, token_present):
    """Render a non-sensitive description of the token state for the UI.

    Deliberately never includes any substring of the actual token —
    CodeQL flags partial-token displays as 'clear-text logging of
    sensitive information', and even a truncated prefix/suffix is more
    information than the user needs at confirm time (they know if they
    pasted a token or not).
    """
    if token_override:
        return "(set by wizard — will be written to /etc/shedos/token)"
    if token_present:
        return "(keep ISO-baked token)"
    return "(none — write /etc/shedos/token via SSH after install)"

# --- Textual app -------------------------------------------------------------

try:
    from textual.app import App, ComposeResult
    from textual.binding import Binding
    from textual.containers import Container, Horizontal, Vertical, VerticalScroll
    from textual.screen import Screen
    from textual.widgets import (
        Button, Footer, Header, Input, Label, RadioButton, RadioSet,
        Static, Switch,
    )
    TEXTUAL_OK = True
except ImportError:
    TEXTUAL_OK = False


def _make_app():
    """Build and return the Textual App class. Done lazily so the rich
    fallback path doesn't import textual unnecessarily.
    """
    from textual.widgets import TabbedContent, TabPane

    class WizardState:
        def __init__(self):
            self.token_override = None
            self.persona = "default"
            self.style = {"terse": True, "formal": False, "emojis": False}
            self.token_present = (
                os.path.exists("/etc/shedos/token")
                and os.path.getsize("/etc/shedos/token") > 0
            )

    STATE = WizardState()

    # BIOS-style: solid dark-blue background, cyan/yellow highlights,
    # hard rectangular borders, monospace everywhere. No animations.
    BIOS_CSS = """
    Screen { background: #00008B; color: #d0d0d0; }

    #title-bar {
        height: 1;
        background: #c0c0c0;
        color: #000080;
        content-align: center middle;
        text-style: bold;
    }
    #bar-bottom {
        height: 1;
        background: #c0c0c0;
        color: #000080;
        content-align: center middle;
    }

    TabbedContent { background: #00008B; }

    TabbedContent > Tabs {
        background: #000050;
        height: 3;
        border-bottom: heavy #00ffff;
    }
    TabbedContent > Tabs Tab {
        background: #000050;
        color: #d0d0d0;
        padding: 0 2;
    }
    TabbedContent > Tabs Tab.-active {
        background: #c0c0c0;
        color: #000080;
        text-style: bold;
    }

    .pane-body {
        padding: 2 4;
        background: #00008B;
    }
    .pane-title {
        text-style: bold underline;
        color: #ffff00;
        margin-bottom: 1;
    }
    .pane-text { color: #ffffff; margin-bottom: 1; }
    .hint      { color: #80c0ff; }
    .err       { color: #ff5555; min-height: 1; }
    .ok        { color: #50fa7b; }

    Input {
        background: #000050;
        color: #ffff00;
        border: tall #00ffff;
    }
    Input:focus { border: tall #ffff00; }

    RadioSet {
        background: #000050;
        border: tall #00ffff;
        padding: 1 2;
        width: 50;
        margin-bottom: 1;
    }
    RadioSet:focus-within { border: tall #ffff00; }
    RadioButton .toggle { color: #ffff00; }

    Switch {
        background: #000050;
        margin: 0 1;
    }
    Switch.-on > .switch--slider { color: #50fa7b; }

    .toggle-row {
        height: 3;
        padding: 0;
        margin-bottom: 1;
        align: left middle;
    }
    .toggle-row Label { width: 12; color: #ffffff; padding: 1 0 0 0; }
    .toggle-row .toggle-desc { width: 1fr; color: #80c0ff; padding: 1 0 0 1; }
    .toggle-row Switch {
        width: 10;
        background: #000050;
    }
    .toggle-row Switch:focus {
        background: #ffff00;
    }

    .summary-row { height: 1; }
    .summary-key { width: 14; color: #ffff00; }
    .summary-val { color: #ffffff; }

    Button {
        background: #c0c0c0;
        color: #000080;
        border: none;
        min-width: 16;
        margin: 1 1 0 0;
    }
    Button:focus { background: #ffff00; color: #000080; text-style: bold; }
    Button.-error   { background: #aa0000; color: #ffffff; }
    Button.-success { background: #008800; color: #ffffff; }
    """

    PANES = [
        ("welcome", "1 Welcome"),
        ("token",   "2 Token"),
        ("persona", "3 Persona"),
        ("style",   "4 Style"),
        ("install", "5 Install"),
    ]

    class WizardApp(App):
        CSS = BIOS_CSS
        TITLE = "ShedOS Setup Utility"

        BINDINGS = [
            Binding("escape",       "cancel",      "Esc Cancel", show=True),
            Binding("left",         "prev_tab",    "← Prev Tab", show=True),
            Binding("right",        "next_tab",    "→ Next Tab", show=True),
            # ↑ / ↓ walk focus between widgets. Widgets that bind these
            # internally (RadioSet, Tabs) still win because focused-widget
            # bindings have higher priority than app-level ones.
            Binding("up",           "focus_previous", "↑ Field", show=False),
            Binding("down",         "focus_next",     "↓ Field", show=False),
            Binding("1",            "tab('welcome')", "", show=False),
            Binding("2",            "tab('token')",   "", show=False),
            Binding("3",            "tab('persona')", "", show=False),
            Binding("4",            "tab('style')",   "", show=False),
            Binding("5",            "tab('install')", "", show=False),
            Binding("f10",          "install",     "F10 Install", show=True),
            Binding("ctrl+c",       "cancel",      "",            show=False),
        ]

        def compose(self) -> ComposeResult:
            yield Static("ShedOS Setup Utility — v0.5.0",
                          id="title-bar")
            with TabbedContent(initial="welcome", id="tabs"):
                with TabPane(PANES[0][1], id="welcome"):
                    with Container(classes="pane-body"):
                        yield Static("Welcome", classes="pane-title")
                        yield Static(
                            "This utility installs Alpine Linux + ShedOS to /dev/sda.\n"
                            "All data on /dev/sda will be ERASED.\n\n"
                            "Use ← / → or the number keys (1..5) to switch tabs.\n"
                            "Use ↑ / ↓ to move between fields. Enter to confirm.\n"
                            "Esc cancels and reboots. F10 starts the install.\n\n"
                            "After confirming, the install runs unattended (~3-5 min)\n"
                            "and the VM reboots into ShedOS.",
                            classes="pane-text",
                        )
                        yield Static(
                            "→ When you're ready, press the [yellow b]→[/] key or hit "
                            "[yellow b]F10[/] to begin.",
                            classes="hint",
                        )

                with TabPane(PANES[1][1], id="token"):
                    with Container(classes="pane-body"):
                        yield Static("Claude Code OAuth token",
                                      classes="pane-title")
                        yield Static(
                            "Paste the token (Cmd+V usually works once vmtoolsd is\n"
                            "up). Leave empty to use the ISO-baked token if any,\n"
                            "or to skip — you can write /etc/shedos/token via SSH\n"
                            "after install.",
                            classes="pane-text",
                        )
                        yield Input(
                            placeholder="sk-ant-oat01-...",
                            password=True,
                            id="token-input",
                        )
                        yield Static("", id="token-err", classes="err")
                        yield Static(
                            f"ISO-baked token present: {'yes' if STATE.token_present else 'no'}",
                            classes="hint",
                        )

                with TabPane(PANES[2][1], id="persona"):
                    with Container(classes="pane-body"):
                        yield Static("Persona", classes="pane-title")
                        yield Static(
                            "Choose how the brain should present itself. You can\n"
                            "switch personas later from the GUI settings panel.",
                            classes="pane-text",
                        )
                        with RadioSet(id="persona-set"):
                            for key, label, _desc in PERSONA_PRESETS:
                                yield RadioButton(label, id=f"p-{key}",
                                                   value=(key == STATE.persona))
                        yield Static("", id="persona-desc", classes="hint")

                with TabPane(PANES[3][1], id="style"):
                    with Container(classes="pane-body"):
                        yield Static("Conversation style",
                                      classes="pane-title")
                        yield Static(
                            "Tunes the brain's responses. All of these are\n"
                            "live-editable from the GUI settings panel later.",
                            classes="pane-text",
                        )
                        for key, label, hint in [
                            ("terse",  "Terse",  "Short replies, minimal narration."),
                            ("formal", "Formal", "Professional tone (vs. casual)."),
                            ("emojis", "Emojis", "Allow emoji in responses."),
                        ]:
                            with Horizontal(classes="toggle-row"):
                                yield Label(label)
                                yield Switch(value=STATE.style[key],
                                              id=f"sw-{key}")
                                yield Static(hint, classes="toggle-desc")

                with TabPane(PANES[4][1], id="install"):
                    with Container(classes="pane-body"):
                        yield Static("Review and install",
                                      classes="pane-title")
                        yield Static("", id="summary", classes="pane-text")
                        with Horizontal():
                            yield Button("Install (F10)",
                                          id="install-btn", variant="success")
                            yield Button("Cancel & reboot (Esc)",
                                          id="cancel-btn", variant="error")
            yield Static("", id="bar-bottom")
            yield Footer()

        # ---- lifecycle -----------------------------------------------------

        def on_mount(self):
            self._refresh_persona_desc(STATE.persona)
            self.query_one("#bar-bottom", Static).update(
                "← → Tabs · ↑ ↓ Field · Enter Confirm · F10 Install · Esc Cancel"
            )

        # ---- helpers -------------------------------------------------------

        def _tabs(self):
            return self.query_one(TabbedContent)

        def _refresh_persona_desc(self, key):
            desc = next((d for k, _, d in PERSONA_PRESETS if k == key), "")
            self.query_one("#persona-desc", Static).update(desc)

        def _refresh_summary(self):
            tok_disp = token_display(STATE.token_override, STATE.token_present)
            persona_label = next(
                (l for k, l, _ in PERSONA_PRESETS if k == STATE.persona),
                STATE.persona,
            )
            style_disp = "  ".join(
                f"{k}={'on' if v else 'off'}" for k, v in STATE.style.items()
            )
            lines = [
                f"  Token         {tok_disp}",
                f"  Persona       {persona_label}",
                f"  Style         {style_disp}",
                "",
                "  /dev/sda will be partitioned and ext4-formatted.",
                "  ALL EXISTING DATA on /dev/sda will be ERASED.",
            ]
            self.query_one("#summary", Static).update("\n".join(lines))

        # ---- bindings ------------------------------------------------------

        def action_prev_tab(self):
            t = self._tabs()
            ids = [p[0] for p in PANES]
            try:
                i = ids.index(t.active)
            except ValueError:
                i = 0
            t.active = ids[max(0, i - 1)]

        def action_next_tab(self):
            t = self._tabs()
            ids = [p[0] for p in PANES]
            try:
                i = ids.index(t.active)
            except ValueError:
                i = 0
            t.active = ids[min(len(ids) - 1, i + 1)]

        def action_tab(self, name):
            self._tabs().active = name

        def action_cancel(self):
            self.exit(result="cancel")

        def action_install(self):
            # Pull values from token input on the fly (the others are
            # bound through their on_*_changed handlers)
            tok = self.query_one("#token-input", Input).value.strip()
            err = self.query_one("#token-err", Static)
            if tok:
                if not looks_like_token(tok):
                    err.update(
                        "Token doesn't look like sk-ant-oat01-… "
                        "Edit it in the Token tab or clear it to skip."
                    )
                    self._tabs().active = "token"
                    self.query_one("#token-input", Input).focus()
                    return
                STATE.token_override = tok
            else:
                STATE.token_override = None
            err.update("")
            self.exit(result="install")

        # ---- event handlers ------------------------------------------------

        def on_tabbed_content_tab_activated(self, event):
            # Auto-update the summary tab when it becomes active
            if event.tab.id and "install" in event.tab.id:
                self._refresh_summary()

        def on_radio_set_changed(self, event: RadioSet.Changed):
            btn_id = event.pressed.id or ""
            if btn_id.startswith("p-"):
                key = btn_id[2:]
                STATE.persona = key
                self._refresh_persona_desc(key)

        def on_switch_changed(self, event: Switch.Changed):
            sid = event.switch.id or ""
            if sid.startswith("sw-"):
                STATE.style[sid[3:]] = event.value

        def on_button_pressed(self, event: Button.Pressed):
            if event.button.id == "install-btn":
                self.action_install()
            elif event.button.id == "cancel-btn":
                self.action_cancel()

    return WizardApp, STATE


def run_textual_wizard():
    WizardApp, STATE = _make_app()
    app = WizardApp()
    result = app.run()
    if result != "install":
        return False
    write_wizard_env(STATE.token_override, STATE.persona, STATE.style)
    return True

# --- rich-based fallback (when Textual isn't available) ---------------------

def _rich():
    try:
        from rich.console import Console
        from rich.panel import Panel
        c = Console(force_terminal=True, color_system="standard")
        def out(m=""): c.print(m)
        def panel(title, body, style="cyan"):
            c.print(Panel(body, title=title, border_style=style, padding=(1, 2)))
        def heading(t): c.rule(f"[bold cyan]{t}[/bold cyan]")
    except ImportError:
        def out(m=""):
            sys.stdout.write(str(m) + "\n"); sys.stdout.flush()
        def panel(title, body, style=None):
            bar = "=" * 60
            out(bar); out(f"  {title}"); out(bar); out(body); out(bar)
        def heading(t):
            out(""); out(f"--- {t} ---"); out("")
    return out, panel, heading


def run_rich_wizard():
    out, panel, heading = _rich()

    def ask_yn(prompt, default_yes=True):
        suffix = " [Y/n]" if default_yes else " [y/N]"
        while True:
            try:
                raw = input(f"{prompt}{suffix}: ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                return default_yes
            if not raw:
                return default_yes
            if raw in ("y", "yes"):
                return True
            if raw in ("n", "no"):
                return False

    def ask_choice(prompt, options, default_idx=0):
        out("")
        for i, (_, label, desc) in enumerate(options, 1):
            marker = " *" if i - 1 == default_idx else "  "
            out(f"  {marker} {i}. {label} — {desc}")
        out("")
        while True:
            try:
                raw = input(f"{prompt} [{default_idx + 1}]: ").strip()
            except (EOFError, KeyboardInterrupt):
                return options[default_idx][0]
            if not raw:
                return options[default_idx][0]
            try:
                n = int(raw)
                if 1 <= n <= len(options):
                    return options[n - 1][0]
            except ValueError:
                pass
            out(f"  ! enter a number between 1 and {len(options)}")

    def ask_token(default_present):
        out("")
        if default_present:
            out("  A Claude Code OAuth token was baked into the ISO at build time.")
            out("  Press Enter to keep it, or paste a new one to override.")
        else:
            out("  No token was baked into the ISO.")
            out("  Paste your Claude Code OAuth token now, or press Enter to skip.")
        out("")
        try:
            raw = getpass.getpass("token (hidden): ").strip()
        except (EOFError, KeyboardInterrupt):
            return None
        if not raw:
            return None
        if not looks_like_token(raw):
            out("  ! that doesn't look like a Claude Code OAuth token.")
            if not ask_yn("  use it anyway?", default_yes=False):
                return ask_token(default_present)
        return raw

    panel("ShedOS installer",
          "Welcome. This will install Alpine Linux + ShedOS to /dev/sda.\n"
          "All data on /dev/sda will be erased.\n\n"
          "The wizard collects a few preferences, then hands off to the\n"
          "installer (~3-5 minutes).",
          style="cyan")
    if not ask_yn("Continue?", default_yes=True):
        return False

    heading("Step 1 of 3 — Claude Code OAuth token")
    token_present = (os.path.exists("/etc/shedos/token")
                     and os.path.getsize("/etc/shedos/token") > 0)
    token_override = ask_token(token_present)

    heading("Step 2 of 3 — Persona")
    out("Choose how the brain should present itself.")
    persona = ask_choice("persona", PERSONA_PRESETS, default_idx=0)

    heading("Step 3 of 3 — Conversation style")
    style = {
        "terse":  ask_yn("Be terse?", default_yes=True),
        "formal": ask_yn("Use a formal tone?", default_yes=False),
        "emojis": ask_yn("Allow emojis?", default_yes=False),
    }

    tok_disp = token_display(token_override, token_present)
    rows = [
        f"  Token         {tok_disp}",
        f"  Persona       {persona}",
        f"  Style         terse={style['terse']}  formal={style['formal']}  emojis={style['emojis']}",
    ]
    panel("Confirm install", "\n".join(rows), style="yellow")
    if not ask_yn("Proceed?", default_yes=True):
        return False

    write_wizard_env(token_override, persona, style)
    return True

# --- main --------------------------------------------------------------------

def _reboot(reason):
    """Cancel path: reboot so the user loops back into the wizard from a
    clean state. We avoid `getty respawn`-style re-exec of run-installer.sh
    because the wizard's tmpfs deps survive across that path; a full reboot
    is a cleaner "I changed my mind, start over" mental model.
    """
    print(f"\n{reason}")
    print("[wizard] rebooting in 3s...")
    import time
    time.sleep(3)
    # Force-sync first; the live system has nothing on disk to lose but
    # the apkovl is in tmpfs and `reboot` is best-effort.
    os.system("sync")
    os.execvp("reboot", ["reboot"])


def main():
    try:
        if TEXTUAL_OK:
            ok = run_textual_wizard()
        else:
            ok = run_rich_wizard()
    except Exception as e:
        # Textual sometimes raises on weird terminals — fall through to rich.
        sys.stderr.write(f"[wizard] textual error: {e!r}\n")
        try:
            ok = run_rich_wizard()
        except Exception as e2:
            sys.stderr.write(f"[wizard] rich error: {e2!r}\n")
            ok = False
    if not ok:
        _reboot("[wizard] cancelled.")
    print("\n[wizard] choices saved; handing off to installer.sh ...\n")
    exec_installer()


if __name__ == "__main__":
    main()
